/* The root user table. */
CREATE TABLE UserInfo (
UserID BIGINT PRIMARY KEY AUTO_INCREMENT,
GID BIGINT NOT NULL,
Email VARCHAR(200) UNIQUE,
PhoneNumber VARCHAR(200) UNIQUE,
WechatID VARCHAR(200) UNIQUE,
WeboID VARCHAR(200) UNIQUE,
HashedPassword VARCHAR(300),
IsConfirm TINYINT NOT NULL,
IsActive TINYINT NOT NULL,
Name VARCHAR(300) NOT NULL,
ImageURL VARCHAR(200),
Area BIGINT NOT NULL,
OtherArea VARCHAR(300),
School BIGINT NOT NULL,
OtherSchool VARCHAR(300),
Company BIGINT NOT NULL,
OtherCompany VARCHAR(300),
SelfDescription VARCHAR(3000),

INDEX (GID)
);

/* Role & Skill tables. */
CREATE TABLE RoleFirstCategory (
RoleFirstCategoryID BIGINT PRIMARY KEY AUTO_INCREMENT,
GID BIGINT NOT NULL,
UserID BIGINT NOT NULL,
RoleFirstCategory BIGINT NOT NULL,

INDEX (GID),
FOREIGN KEY (UserID) REFERENCES UserInfo(UserID)
ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE RoleSecondCategory (
RoleSecondCategoryID BIGINT PRIMARY KEY AUTO_INCREMENT,
RoleFirstCategoryID BIGINT NOT NULL,
RoleSecondCategory BIGINT NOT NULL,

FOREIGN KEY (RoleFirstCategoryID) REFERENCES RoleFirstCategory(RoleFirstCategoryID)
ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Skill (
SkillID BIGINT PRIMARY KEY AUTO_INCREMENT,
RoleFirstCategoryID BIGINT NOT NULL,
Skill VARCHAR(300) NOT NULL,

FOREIGN KEY (RoleFirstCategoryID) REFERENCES RoleFirstCategory(RoleFirstCategoryID)
ON DELETE CASCADE ON UPDATE NO ACTION
);

/* Project tables. */
CREATE TABLE ProjectInfo (
ProjectID BIGINT PRIMARY KEY AUTO_INCREMENT,
GID BIGINT NOT NULL,
UserID BIGINT NOT NULL,
Name VARCHAR(300) NOT NULL,
ProjectType BIGINT NOT NULL,
URL VARCHAR(200),
Position VARCHAR(300),
StartDate DATE,
EndDate DATE,
Synopsis VARCHAR(3000),
Producer VARCHAR(300),
Remark VARCHAR(3000),

INDEX (GID),
FOREIGN KEY (UserID) REFERENCES UserInfo(UserID)
ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE ProjectPartner (
PartnerID BIGINT PRIMARY KEY AUTO_INCREMENT,
ProjectID BIGINT NOT NULL,
UserID BIGINT,
Name VARCHAR(300),

FOREIGN KEY (ProjectID) REFERENCES ProjectInfo(ProjectID)
ON DELETE CASCADE ON UPDATE NO ACTION,
FOREIGN KEY (UserID) REFERENCES UserInfo(UserID)
ON DELETE NO ACTION ON UPDATE NO ACTION
);

/* Relationship tables. */
CREATE TABLE Friendship (
FriendshipID BIGINT PRIMARY KEY AUTO_INCREMENT,
UserID BIGINT NOT NULL,
FriendID BIGINT NOT NULL,

FOREIGN KEY (UserID) REFERENCES UserInfo(UserID)
ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY (FriendID) REFERENCES UserInfo(UserID)
ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE FriendTag (
FriendTagID BIGINT PRIMARY KEY AUTO_INCREMENT,
FriendshipID BIGINT NOT NULL,
Tag VARCHAR(300) NOT NULL,

FOREIGN KEY (FriendshipID) REFERENCES Friendship(FriendshipID)
ON DELETE CASCADE ON UPDATE NO ACTION
);
